import Handlebars from "handlebars";
import { TEMPLATE_CONTENT } from "./content";
import type { TemplateType } from "@/generated/prisma/enums";

export type DocumentPdfData = {
  documentId: string;
  documentTitle: string;
  templateType: TemplateType;
  effectiveDate: string;
  companyName: string;
  companyAddress: string;
  counterpartyName: string;
  counterpartyEmail: string;
  companySignerName: string;
  companySignerRole: string;
  companySignedAt: string | null;
  companySignatureData: string | null;
  counterpartySignedAt: string | null;
  counterpartySignatureData: string | null;
};

const SHELL = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  @page { size: letter; margin: 0.9in 0.85in 1in 0.85in; }
  * { box-sizing: border-box; }
  body {
    font-family: 'Times New Roman', Georgia, serif;
    font-size: 11.5pt;
    line-height: 1.5;
    color: #16181c;
    margin: 0;
  }
  .letterhead {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    border-bottom: 1.5pt solid #16181c;
    padding-bottom: 8pt;
    margin-bottom: 20pt;
  }
  .letterhead .company {
    font-family: Helvetica, Arial, sans-serif;
    font-weight: 700;
    font-size: 11pt;
    letter-spacing: 0.02em;
  }
  .letterhead .meta {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 8.5pt;
    color: #555;
    text-align: right;
  }
  h1 {
    font-size: 15pt;
    text-align: center;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    margin: 0 0 18pt 0;
  }
  .recital {
    text-align: justify;
    margin-bottom: 16pt;
  }
  .clause { margin-bottom: 11pt; text-align: justify; }
  .clause h2 {
    font-size: 11.5pt;
    font-weight: 700;
    display: inline;
  }
  .clause .body { display: inline; }
  .signatures {
    margin-top: 34pt;
    display: flex;
    justify-content: space-between;
    gap: 36pt;
    break-inside: avoid;
    page-break-inside: avoid;
  }
  .sig-block {
    flex: 1;
    min-width: 0;
    font-family: Helvetica, Arial, sans-serif;
    font-size: 9pt;
  }
  .sig-line {
    border-top: 1pt solid #16181c;
    margin-top: 34pt;
    padding-top: 4pt;
  }
  .sig-image {
    height: 30pt;
    max-width: 100%;
    width: auto;
    display: block;
    margin-bottom: 2pt;
  }
  .sig-caption { color: #555; margin-top: 2pt; }
</style>
</head>
<body>
  <div class="letterhead">
    <div class="company">{{companyName}}</div>
    <div class="meta">{{companyAddress}}</div>
  </div>

  <h1>{{templateLabel}}</h1>

  <div class="recital">{{{recital}}}</div>

  {{#each clauses}}
  <div class="clause">
    <h2>{{this.heading}}</h2>
    <span class="body">&nbsp;{{{this.body}}}</span>
  </div>
  {{/each}}

  <div class="signatures">
    <div class="sig-block">
      {{#if companySignatureData}}
        <img class="sig-image" src="{{companySignatureData}}" />
      {{/if}}
      <div class="sig-line">
        {{companySignerName}}<br />
        {{companySignerRole}}, {{companyName}}
      </div>
      <div class="sig-caption">
        {{#if companySignedAt}}Signed {{companySignedAt}}{{else}}Awaiting signature{{/if}}
      </div>
    </div>
    <div class="sig-block">
      {{#if counterpartySignatureData}}
        <img class="sig-image" src="{{counterpartySignatureData}}" />
      {{/if}}
      <div class="sig-line">
        {{counterpartyName}}<br />
        {{counterpartyEmail}}
      </div>
      <div class="sig-caption">
        {{#if counterpartySignedAt}}Signed {{counterpartySignedAt}}{{else}}Awaiting signature{{/if}}
      </div>
    </div>
  </div>

</body>
</html>`;

const compiled = Handlebars.compile(SHELL, { noEscape: false });

export function renderDocumentHtml(data: DocumentPdfData): string {
  const content = TEMPLATE_CONTENT[data.templateType];

  const recitalCompiled = Handlebars.compile(content.recital, {
    noEscape: true,
  })(data);
  const clauses = content.clauses.map((clause) => ({
    heading: clause.heading,
    body: Handlebars.compile(clause.body, { noEscape: true })(data),
  }));

  return compiled({
    ...data,
    templateLabel: content.label,
    recital: recitalCompiled,
    clauses,
  });
}

export function renderFooterHtml(data: DocumentPdfData): string {
  // Puppeteer renders this as its own isolated document per page, styled
  // independently of the main page CSS — font sizes here are plain px.
  return `<div style="font-family:Helvetica,Arial,sans-serif;font-size:7px;color:#888;width:100%;text-align:center;">
    ${data.documentTitle} &middot; Ref ${data.documentId} &middot; Generated by Countersign (demo)
  </div>`;
}
