import { spawn } from "node:child_process";
import { createServer } from "node:net";
import os from "node:os";
import path from "node:path";
import { Client } from "pg";
import { assertLocalDatabaseUrl } from "../../src/lib/database-target";

// Throwaway Postgres for the test suite. Two sources, both local-only:
//
//   - TEST_DATABASE_URL set (CI's service container, or any local server
//     you point it at): used as an admin connection to create and drop
//     per-run databases. Must be a localhost URL.
//   - otherwise: a real PostgreSQL binary (embedded-postgres) started in a
//     fresh OS temp directory, deleted again when the run ends.
//
// Production connection strings (.env's DATABASE_URL / DIRECT_URL) are
// never read here.

export type TestServer = {
  adminUrl: string;
  stop: () => Promise<void>;
};

const TEMP_DIR_PREFIX = "countersign-test-pg-";

async function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = createServer();
    server.unref();
    server.on("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const { port } = server.address() as { port: number };
      server.close(() => resolve(port));
    });
  });
}

async function startEmbedded(runId: string): Promise<TestServer> {
  const { default: EmbeddedPostgres } = await import("embedded-postgres");

  const tempRoot = path.resolve(os.tmpdir());
  const databaseDir = path.join(tempRoot, `${TEMP_DIR_PREFIX}${runId}`);
  // embedded-postgres deletes databaseDir on stop (persistent: false), so
  // make sure it can only ever be a fresh directory inside the OS temp dir.
  if (
    path.dirname(databaseDir) !== tempRoot ||
    !path.basename(databaseDir).startsWith(TEMP_DIR_PREFIX)
  ) {
    throw new Error("Refusing to use an unexpected test database directory.");
  }

  const port = await freePort();
  const pg = new EmbeddedPostgres({
    databaseDir,
    port,
    user: "countersign_test",
    password: "countersign_test",
    persistent: false,
    // PostgreSQL 18 defaults to io_method=worker, whose io_worker processes
    // survive embedded-postgres's Windows shutdown (taskkill /t) as orphans.
    // Synchronous I/O starts no extra processes and is plenty for tests.
    postgresFlags: ["-c", "io_method=sync"],
    onLog: () => {},
    onError: () => {},
  });
  await pg.initialise();
  await pg.start();

  return {
    adminUrl: `postgresql://countersign_test:countersign_test@127.0.0.1:${port}/postgres`,
    stop: () => pg.stop(),
  };
}

export async function startTestServer(runId: string): Promise<TestServer> {
  const external = process.env.TEST_DATABASE_URL;
  if (external) {
    return {
      adminUrl: assertLocalDatabaseUrl(external, "TEST_DATABASE_URL"),
      stop: async () => {},
    };
  }
  return startEmbedded(runId);
}

export function databaseUrl(adminUrl: string, database: string): string {
  const url = new URL(adminUrl);
  url.pathname = `/${database}`;
  return url.toString();
}

// Identifiers are generated by the harness, never by user input; this check
// keeps them safe to interpolate into CREATE/DROP DATABASE.
function assertIdentifier(name: string): string {
  if (!/^[a-z0-9_]{1,63}$/.test(name)) {
    throw new Error(`Unsafe test database name: ${name}`);
  }
  return name;
}

export async function adminQuery<T = unknown>(
  adminUrl: string,
  sql: string,
): Promise<T[]> {
  const client = new Client({ connectionString: assertLocalDatabaseUrl(adminUrl, "test admin") });
  await client.connect();
  try {
    const result = await client.query(sql);
    return result.rows as T[];
  } finally {
    await client.end();
  }
}

export async function createDatabase(adminUrl: string, name: string, template?: string) {
  const from = template ? ` TEMPLATE "${assertIdentifier(template)}"` : "";
  await adminQuery(adminUrl, `CREATE DATABASE "${assertIdentifier(name)}"${from}`);
}

export async function dropDatabasesWithPrefix(adminUrl: string, prefix: string) {
  const rows = await adminQuery<{ datname: string }>(
    adminUrl,
    "SELECT datname FROM pg_database WHERE NOT datistemplate",
  );
  for (const { datname } of rows) {
    if (!datname.startsWith(assertIdentifier(prefix))) continue;
    await adminQuery(adminUrl, `DROP DATABASE IF EXISTS "${assertIdentifier(datname)}" WITH (FORCE)`);
  }
}

// Applies the real migrations with the real CLI, so every test run also
// proves the migration history applies cleanly to an empty database.
export async function migrate(url: string): Promise<void> {
  assertLocalDatabaseUrl(url, "migrate");
  const prismaCli = path.resolve("node_modules/prisma/build/index.js");

  await new Promise<void>((resolve, reject) => {
    const child = spawn(process.execPath, [prismaCli, "migrate", "deploy"], {
      // prisma.config.ts prefers DIRECT_URL, and loads .env without
      // overriding variables that are already set — so both are pinned to
      // the throwaway database here, never left to fall back to .env.
      env: { ...process.env, DATABASE_URL: url, DIRECT_URL: url },
      stdio: ["ignore", "pipe", "pipe"],
    });
    let output = "";
    child.stdout.on("data", (chunk) => (output += chunk));
    child.stderr.on("data", (chunk) => (output += chunk));
    child.on("error", reject);
    child.on("exit", (code) =>
      code === 0
        ? resolve()
        : reject(new Error(`prisma migrate deploy failed (exit ${code}):\n${output}`)),
    );
  });
}
